rm version_defs.h
printf "// Copyright (C) 2018 Christian Sailer\n" >> version_defs.h

printf "// This program is free software: you can redistribute it and/or modify\n" >> version_defs.h
printf "// it under the terms of the GNU General Public License as published by\n" >> version_defs.h
printf "// the Free Software Foundation, either version 3 of the License, or\n" >> version_defs.h
printf "// (at your option) any later version.\n\n" >> version_defs.h
printf "// This program is distributed in the hope that it will be useful,\n" >> version_defs.h
printf "// but WITHOUT ANY WARRANTY\; without even the implied warranty of\n" >> version_defs.h
printf "// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n" >> version_defs.h
printf "// GNU General Public License for more details.\n\n" >> version_defs.h
printf "// You should have received a copy of the GNU General Public License\n" >> version_defs.h
printf "// along with this program.  If not, see <http://www.gnu.org/licenses/>.\n\n" >> version_defs.h

printf "// This file is autogenerated - do not modify it directly!\n\n" >> version_defs.h

printf "#pragma once\n\n" >> version_defs.h

printf "#ifndef APP_DATE\n" >> version_defs.h
printf "#define APP_DATE \"`date +%Y/%m/%d`\"\n" >> version_defs.h
printf "#endif\n\n" >> version_defs.h

printf "#ifndef APP_GIT_BRANCH\n" >> version_defs.h
printf "#define APP_GIT_BRANCH \"`git rev-parse --abbrev-ref HEAD`\"\n" >> version_defs.h
printf "#endif\n\n" >> version_defs.h

printf "#ifndef APP_GIT_COMMIT\n" >> version_defs.h
printf "#define APP_GIT_COMMIT \"`git log --pretty=format:'%h' -n 1`\"\n" >> version_defs.h
printf "#endif\n" >> version_defs.h

