uic -o ../CompiledUI/ui_AboutDlg.h AboutDlg.ui
uic -o ../CompiledUI/ui_AgentAnalysisDlg.h AgentAnalysisDlg.ui
uic -o ../CompiledUI/ui_AttributeChooserDlg.h AttributeChooserDlg.ui
uic -o ../CompiledUI/ui_AttributeSummary.h AttributeSummary.ui
uic -o ../CompiledUI/ui_AxialAnalysisOptionsDlg.h AxialAnalysisOptionsDlg.ui
uic -o ../CompiledUI/ui_ColourScaleDlg.h ColourScaleDlg.ui
uic -o ../CompiledUI/ui_ColumnPropertiesDlg.h ColumnPropertiesDlg.ui
uic -o ../CompiledUI/ui_ConvertShapesDlg.h ConvertShapesDlg.ui
uic -o ../CompiledUI/ui_DepthmapAlert.h DepthmapAlert.ui
uic -o ../CompiledUI/ui_DepthmapOptionsDlg.h DepthmapOptionsDlg.ui
uic -o ../CompiledUI/ui_EditConnectionsDlg.h EditConnectionsDlg.ui
uic -o ../CompiledUI/ui_FewestLineOptionsDlg.h FewestLineOptionsDlg.ui
uic -o ../CompiledUI/ui_FilePropertiesDlg.h FilePropertiesDlg.ui
uic -o ../CompiledUI/ui_FindLocDlg.h FindLocDlg.ui
uic -o ../CompiledUI/ui_GridDialog.h GridDialog.ui
uic -o ../CompiledUI/ui_InsertColumnDlg.h InsertColumnDlg.ui
uic -o ../CompiledUI/ui_IsovistPathDlg.h IsovistPathDlg.ui
uic -o ../CompiledUI/ui_LayerChooserDlg.h LayerChooserDlg.ui
uic -o ../CompiledUI/ui_LicenceDialog.h LicenceDialog.ui
uic -o ../CompiledUI/ui_MakeLayerDlg.h MakeLayerDlg.ui
uic -o ../CompiledUI/ui_MakeOptionsDlg.h MakeOptionsDlg.ui
uic -o ../CompiledUI/ui_NewLayerDlg.h NewLayerDlg.ui
uic -o ../CompiledUI/ui_OptionsDlg.h OptionsDlg.ui
uic -o ../CompiledUI/ui_PromptReplace.h PromptReplace.ui
uic -o ../CompiledUI/ui_PushDialog.h PushDialog.ui
uic -o ../CompiledUI/ui_RenameObjectDlg.h RenameObjectDlg.ui
uic -o ../CompiledUI/ui_SegmentAnalysisDlg.h SegmentAnalysisDlg.ui
uic -o ../CompiledUI/ui_TopoMetDlg.h TopoMetDlg.ui
